#!/bin/bash
echo "🚀 Setup Monitoring - MemoLib"
echo ""
echo "1. Créer compte Sentry: https://sentry.io/signup/"
echo "2. Créer nouveau projet Next.js"
echo "3. Copier DSN"
echo ""
echo "4. Ajouter à .env.local:"
echo "   SENTRY_DSN=https://xxx@xxx.ingest.sentry.io/xxx"
echo "   NEXT_PUBLIC_SENTRY_DSN=https://xxx@xxx.ingest.sentry.io/xxx"
echo ""
echo "5. Tester:"
echo "   npm run dev"
echo "   curl http://localhost:3000/api/health"
echo ""
echo "✅ Fichiers créés:"
echo "   - sentry.client.config.ts"
echo "   - sentry.server.config.ts"
echo "   - sentry.edge.config.ts"
echo "   - instrumentation.ts"
echo "   - src/app/api/health/route.ts"
echo "   - docs/MONITORING_SETUP.md"
