DO $$ BEGIN
  CREATE TYPE "DeadlineType" AS ENUM ('OQTF_48H', 'OQTF_15J', 'OQTF_30J', 'RECOURS_TA', 'RECOURS_CNDA', 'AUDIENCE', 'RDV_PREFECTURE', 'TITRE_EXPIRATION', 'CUSTOM');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "DeadlineStatus" AS ENUM ('PENDING', 'APPROACHING', 'URGENT', 'CRITICAL', 'OVERDUE', 'COMPLETED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
